# Generated by Django 6.0.2 on 2026-05-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('mother_tongue', models.CharField(default='Kannada', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('programme', models.CharField(choices=[('Veda (Vedic Studies)', 'Veda (Vedic Studies)'), ('Vedic Chanting', 'Vedic Chanting (Kramapatha / Ghanapatha)'), ('Sanskrit Language', 'Sanskrit Language & Grammar (Ashtadhyayi)'), ('Jyotisha', 'Jyotisha (Vedic Astrology)'), ('Ayurveda', 'Ayurveda Foundation'), ('Yoga', 'Yoga & Meditation'), ('Vedic Mathematics', 'Vedic Mathematics'), ('Purohit Training', 'Purohit Training (Ritual Procedures)'), ('General Studies', 'General Vedic Studies')], max_length=100)),
                ('duration', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('Short Course', 'Short Course (3–6 months)')], default='1 Year', max_length=50)),
                ('mode', models.CharField(choices=[('Residential', 'Residential (Gurukul)'), ('Day Scholar', 'Day Scholar'), ('Online', 'Online')], default='Residential', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('prior_knowledge', models.TextField(blank=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('last_school', models.CharField(blank=True, max_length=255)),
                ('last_class', models.CharField(blank=True, max_length=50)),
                ('year_passing', models.CharField(blank=True, max_length=4)),
                ('percentage', models.CharField(blank=True, max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('reference_source', models.CharField(blank=True, max_length=100)),
                ('reference_person', models.CharField(blank=True, max_length=100)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
    ]
