# Generated by Django 6.0.2 on 2026-05-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
