# Generated by Django 6.0.2 on 2026-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_student_declaration_accepted_student_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc_address_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_birth_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_marksheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_vedic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A−'), ('B+', 'B+'), ('B-', 'B−'), ('O+', 'O+'), ('O-', 'O−'), ('AB+', 'AB+'), ('AB-', 'AB−')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_source',
            field=models.CharField(blank=True, choices=[('Word of Mouth', 'Word of Mouth / Family'), ('Alumni', 'Former Student / Alumni'), ('Temple', 'Temple / Ashram'), ('Social Media', 'Social Media'), ('Website', 'Website'), ('Newspaper', 'Newspaper / Magazine'), ('Other', 'Other')], max_length=100),
        ),
    ]
