# Generated by Django 6.0.2 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_student_doc_address_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shiva_deeksha',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
