# Generated by Django 6.0.2 on 2026-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_student_shiva_deeksha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='doc_address_proof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='doc_birth_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='doc_income',
        ),
        migrations.RemoveField(
            model_name='student',
            name='doc_marksheet',
        ),
        migrations.RemoveField(
            model_name='student',
            name='doc_medical',
        ),
        migrations.RemoveField(
            model_name='student',
            name='doc_photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='doc_vedic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='student',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prior_knowledge',
        ),
        migrations.RemoveField(
            model_name='student',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reference_person',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reference_source',
        ),
        migrations.RemoveField(
            model_name='student',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
